config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy'


  namespace :guest_tutorial, path: "tutorial" do
    resources :introductions, only: %i[index]
  end
  namespace :guest_tutorial, path: "tutorial" do
    resources :how_to_recordings, only: %i[index]
  end

  # ゲスト投稿閲覧についての設定
  scope :guest do
    resources :posts, only: %i[index show], as: :guest
  end

  resources :posts
  resources :recordings, only: %i[new create]
  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  # letter_opener_webにアクセスするためのルーティング設定
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/guest_tutorial/how_to_recordings_controller.rb
class GuestTutorial::HowToRecordingsController < ApplicationController
  skip_before_action :require_login
  def index
    if params[:level]
      @level = params[:level]
    else
      redirect_to guest_tutorial_introductions_path
    end

  end

end

app/controllers/guest_tutorial/introductions_controller.rb
class GuestTutorial::IntroductionsController < ApplicationController
  skip_before_action :require_login
  def index
  end
end

app/helpers/guest_tutorial/how_to_recordings_helper.rb
module GuestTutorial::HowToRecordingsHelper
  def by_level_title(level)
    case level
    when "easy"
      "初級： クリック音に合わせてパルマ(手拍子)を叩いてみよう!!"
    when "normal"
      "中級： ギターのタパに合わせてパルマ(手拍子)を叩こう!!"
    when "hard"
      "上級： 実践!! ギターのフレーズに合わせてパルマ(手拍子)を叩こう!!"
    end
  end
end

app/helpers/guest_tutorial/introductions_helper.rb
module GuestTutorial::IntroductionsHelper
end

app/views/guest_tutorial/how_to_recordings/index.html.erb
<div class="bkg-img-index text-white">
  <p class="fs-2 pt-2 ps-4">RECORDING</p>
  <div class="container">
    <div class="text-center mb-4" id="level-select">
      <%# how_to_recordings_helper.rbでメソッド作成 %>
      <h1 class="fs-2 fw-bold"><%= by_level_title(@level) %></h1>
    </div>
    <div class="d-flex justify-content-center mb-4">
      <%= render "layouts/guest_tutorial/#{@level}_help_text" %>
    </div>

    <%# 録音 %>
    <div class="pt-4 pb-3 mt-5 mb-5">
      <h3 class="text-center mb-4">↓↓ レコーディング開始!! ↓↓</h3>
      <div class="mb-3">
        <div class="mb-5 d-flex justify-content-center">
          <%= render "layouts/guest_tutorial/recording_btn" %>
        </div>
        <div class="d-flex justify-content-center">
          <%= render "layouts/guest_tutorial/audio_slider", slider_type: "tutorial-record", slider_size: "50" %>
        </div>
      </div>
    </div>

    <% if @level == 'hard' %>
      <div class="d-flex justify-content-center pb-5">
        <%= link_to "みんなの投稿を見る", guest_index_path, class: "btn btn-lg btn-custom text-white rounded-pill px-3 py-3 fw-bold" , type: "button" %>
      </div>
    <% else %>
      <div class="d-flex justify-content-center pb-5">
        <%= link_to "次のステップへ", guest_tutorial_introductions_path, class: "btn btn-lg btn-custom text-white rounded-pill px-3 py-3 fw-bold" , type: "button" %>
      </div>
    <% end %>

  </div>
</div>

<%# js読み込み %>
<%= javascript_pack_tag 'audio-playback' %>
<%= javascript_pack_tag 'create-audio' %>