config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy'


  namespace :guest_tutorial, path: "tutorial" do
    resources :introductions, only: %i[index]
  end
  namespace :guest_tutorial, path: "tutorial" do
    resources :how_to_recordings, only: %i[index]
  end

  # ゲスト投稿閲覧についての設定
  scope :guest do
    resources :posts, only: %i[index show], as: :guest
  end

  resources :posts
  resources :recordings, only: %i[new create]
  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  # letter_opener_webにアクセスするためのルーティング設定
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer>
  <nav class="navbar bg-color">
    <div class="container-fluid">
      <div class="nav-item">
        <a class="navbar-brand text-white fs-6" href="#">お問い合わせ</a>
        <a class="navbar-brand text-white fs-6" href="#">利用規約</a>
        <a class="navbar-brand text-white fs-6" href="#">プライバシーポリシー</a>
      </div>
    </div>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light shadow-sm sticky-top bg-color">
    <div class="container-fluid">
      <div>
        <%= image_pack_tag "media/images/music_icon.png", class: "mb-2", size: 5*5 %>
        <a class="navbar-brand text-white fw-bold" href="/">フラッと×セッション</a>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li><%= link_to "投稿を見る", posts_path, class: "nav-link text-white active" %></li>
          <%# アクセス制限 %>
          <% if logged_in? %>
            <li><%= link_to "録音する", new_post_path, class: "nav-link text-white" %></li>
            
            <li>
              <div class="dropdown">
                <a href="#" class="nav-link dropdown-toggle" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                  
                  <%# FIXME: アバターパスのエラーの対応で一時的に変更（app/helpers/application_helper.rbでメソッド使用） %>
                  <%#= image_tag current_user.avatar_url, class: 'rounded-circle mr15', size: '30x30'%>
                  <%= avatar_image_tag(current_user, 'rounded-circle mr15', '30x30') %>

                </a>
                
                <div class='dropdown-menu dropdown-menu-end'>
                  <div class='dropdown-item'><%= current_user.name %></div>
                  <div class='dropdown-divider'></div>
                  <%= link_to 'プロフィール詳細', profile_path, class: 'dropdown-item' %>
                  <%= link_to 'ログアウト', logout_path, class: 'dropdown-item', method: :delete %>
                </div>
              </div>
            </li>
            
          <% else %>
            <li><%= link_to "登録", new_user_path, class:"nav-link text-white" %></li>
            <li><%= link_to 'ログイン', login_path, class: 'nav-link text-white' %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_how_to_use_app.html.erb
<div class="bg-dark-custom py-5">
  <div class="text-white text-center">
    <h1 class="fw-bold">アプリの使い方</h1>
  </div>

  <section>
    <div class="py-5 px-4" id="explain-recording">
      <div class="container">
        <h2 class="text-white fw-bold">①録音する</h2>
        <div class="d-lg-flex flex-row">
          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP1：録音画面へ移動</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-2">①投稿一覧画面に移動</p>
                  <p>②録音ボタンを押す</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>
          
          <div class="text-center align-self-lg-center text-white mx-3">
            <i class="fa-solid fa-angle-right fa-3x d-none d-lg-block"></i>
            <i class="fa-solid fa-angle-down fa-3x d-lg-none"></i>
          </div>
          
          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP2：録音開始</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-2">①recボタン押して録音開始/stopボタンで停止</p>
                  <p>②play＆pauseボタンで音声確認したらnextボタンでフォームへ移動</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>

          <div class="text-center align-self-lg-center text-white mx-3">
            <i class="fa-solid fa-angle-right fa-3x d-none d-lg-block"></i>
            <i class="fa-solid fa-angle-down fa-3x d-lg-none"></i>
          </div>
          
          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP3：投稿する</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-2">①タイトル・詳細・公開設定を記入</p>
                  <p>②投稿ボタンを押して投稿完了</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="bg-dark-sub-custom py-5 px-4" id="explain-collab">
      <div class="container">
        <h2 class="text-white fw-bold">②セッションする</h2>
        <div class="d-lg-flex flex-row">
          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP1：録音画面へ移動</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-2">①投稿一覧画面に移動</p>
                  <p class="mb-2">②気になる投稿を見つけて詳細ボタンを押す</p>
                  <p class="mb-1">③セッションボタンを押す</p>
                  <p class="fs-6">補足：一覧画面/セッションボタンを押した場合はサンプル音源が元音声になります</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>

          <div class="text-center align-self-lg-center text-white mx-3">
            <i class="fa-solid fa-angle-right fa-3x d-none d-lg-block"></i>
            <i class="fa-solid fa-angle-down fa-3x d-lg-none"></i>
          </div>

          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP2：セッション開始</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-1">①recボタンを押す/stopボタンで録音停止</p>
                  <p class="fs-6 mb-3">補足：スピーカー上で流れる元音声に合わせて録音開始</p>
                  <p>②play＆pauseボタンで音声確認したらnextボタンでフォームへ移動</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>

          <div class="text-center align-self-lg-center text-white mx-3">
            <i class="fa-solid fa-angle-right fa-3x d-none d-lg-block"></i>
            <i class="fa-solid fa-angle-down fa-3x d-lg-none"></i>
          </div>

          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP3：投稿する</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-2">①タイトル・詳細・公開設定を記入</p>
                  <p>②投稿ボタンを押して投稿完了</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section>
    <div class="py-5 px-4" id="explain-tutorial">
      <div class="container px-4">
        <h2 class="text-white fw-bold">③体験する</h2>
        <div class="d-lg-flex flex-row">
          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP1：チュートリアルへ移動</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-2">①トップページの「はじめるボタン」を押す</p>
                  <p class="mb-1">②選択画面でチュートリアルを選択</p>
                  <p class="fs-6 mb-3">補足：投稿閲覧を選択した場合はコラボ録音機能の体験ができます</p>
                  <p class="fs-6">※新規投稿はログインユーザーのみ可能</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>

          <div class="text-center align-self-lg-center text-white mx-3">
            <i class="fa-solid fa-angle-right fa-3x d-none d-lg-block"></i>
            <i class="fa-solid fa-angle-down fa-3x d-lg-none"></i>
          </div>

          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP2：パルマ（手拍子）のやり方＆難易度の選択</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-2">①パルマ（手拍子）のやり方を確認</p>
                  <p class="mb-1">②難易度を選択すると録音画面へ移動</p>
                  <p class="fs-6">補足：難易度1または2以降に難易度3への挑戦がオススメ</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>

          <div class="text-center align-self-lg-center text-white mx-3">
            <i class="fa-solid fa-angle-right fa-3x d-none d-lg-block"></i>
            <i class="fa-solid fa-angle-down fa-3x d-lg-none"></i>
          </div>

          <div class="col">
            <div class="card h-100 p-2">
              <div class="card-body font-monospace">
                <h3 class="card-title fw-bold mb-4">STEP3：パルマ（手拍子）を叩いて録音</h3>
                <div class="card-text fw-bold fs-5 px-3">
                  <p class="mb-2">①録音方法、お手本音声を確認する</p>
                  <p class="mb-2">②recボタンで録音開始/stopボタンで録音停止</p>
                  <p>③play＆pauseボタンで録音した音声を確認</p>
                </div>
              </div>
              <%# 画像は仮で設定 %>
              <div class="d-flex justify-content-center pb-4">
                <%= image_pack_tag "media/images/録音テキスト1.png", size: "225x400" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/shared/_posts_list.html.erb
<div class="row row-cols-1 row-cols-md-2 g-5">
  <% posts.each do |post| %>
    <div class="col">
      <div class="card">
        <%# 条件定義でpresent?をつけるかどうか？ %>
        <% if post.collab_src.present? %>
          <p><%= "【コラボ投稿】" %></p>
        <% else %>
          <p><%= "【投稿】" %></p>
        <% end %>
        <p><%= post.user.name %></p>


        <div class="card-body">
          <p>
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= post.body %></p>
            <p class="my-2">
              <% if post.voice.attached? %>
                <%= audio_tag(url_for(post.voice), controls: true) %>
              <% end %>
            </p>
            <div class="btn-toolbar">
              <div class="btn-group ms-auto" role="group" aria-label="Basic outlined example">
                <%= link_to '詳細', post_path(post), class: "btn btn-outline-primary", type: "button"  %>
                <%# ログインしているか・投稿者本人かを確認 %>
                <% if logged_in? && current_user.id == post.user.id %>
                  <%= link_to '編集', edit_post_path(post), class: "btn btn-outline-primary", type: "button"  %>
                  <%= link_to '削除', post_path(post, current_page: 'profile'), method: "delete", data: { confirm: "削除しますか？"}, class: "btn btn-outline-primary", type: "button"   %>
                <% end %>
              </div>
            </div>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>