config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy'


  namespace :guest_tutorial, path: "tutorial" do
    resources :introductions, only: %i[index]
  end
  namespace :guest_tutorial, path: "tutorial" do
    resources :how_to_recordings, only: %i[index]
  end

  # ゲスト投稿閲覧についての設定
  scope :guest do
    resources :posts, only: %i[index show], as: :guest
  end

  resources :posts
  resources :recordings, only: %i[new create]
  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  # letter_opener_webにアクセスするためのルーティング設定
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/guest_tutorial/how_to_recordings_controller.rb
class GuestTutorial::HowToRecordingsController < ApplicationController
  skip_before_action :require_login
  def index
    if params[:level]
      @level = params[:level]
    else
      redirect_to guest_tutorial_introductions_path
    end

  end

end

app/controllers/guest_tutorial/introductions_controller.rb
class GuestTutorial::IntroductionsController < ApplicationController
  skip_before_action :require_login
  def index
  end
end

app/helpers/guest_tutorial/how_to_recordings_helper.rb
module GuestTutorial::HowToRecordingsHelper
  def by_level_title(level)
    case level
    when "easy"
      "初級： クリック音に合わせてパルマ(手拍子)を叩いてみよう!!"
    when "normal"
      "中級： ギターのタパに合わせてパルマ(手拍子)を叩こう!!"
    when "hard"
      "上級： 実践!! ギターのフレーズに合わせてパルマ(手拍子)を叩こう!!"
    end
  end
end

app/helpers/guest_tutorial/introductions_helper.rb
module GuestTutorial::IntroductionsHelper
end

app/views/layouts/guest_tutorial/_audio_slider.html.erb
<%# WebAudioAPIでコントローラー作成 %>
<div class="js-audio-player-container bg-custom-audio-slider border border-secondary border-3 rounded-pill d-flex align-items-center w-<%= "#{slider_size}" %> py-2 px-4">
  <% if defined?(audio_blob_url) && !defined?(audio_data_url) %>
    <button type="button"
            class= "<%= "#{slider_type}" %>-playback btn btn-outline-danger border border-danger border-3 fst-italic me-2"
            data-audio-url= "<%= rails_blob_path(audio_blob_url, disposition: "attachment") %>" >
      Play
    </button>
  <% elsif defined?(audio_data_url) && !defined?(audio_blob_url) %>
    <button type="button"
            class="<%= "#{slider_type}" %>-playback btn btn-outline-danger border border-danger border-3 fst-italic me-2"
            data-audio-url= <%= audio_data_url %> >
      Play
    </button>
  <% else %>
    <button type="button" class="<%= "#{slider_type}" %>-playback btn btn-outline-danger border border-danger border-3 fst-italic me-2">Play</button>
  <% end %>

  <button type="button" class="<%= "#{slider_type}" %>-stop btn btn-outline-primary border border-primary border-3 fst-italic me-3" disabled>Pause</button>
  <span class="<%= "#{slider_type}" %>-playback-time text-white">0:00</span>
  <input class="<%= "#{slider_type}" %>-slider ms-2" type="range" min="0" max="100" value="0" style="width: 80%;">
</div>

app/views/layouts/guest_tutorial/_easy_help_text.html.erb
<div class="card border border-2 border-white bg-color card-shadow-dark w-75">
  <div class="card-body text-white">
    <div class="card-text mb-5">
      <div class="mb-5">
        <h3 >使い方説明</h3>
        <ol>
          <li>録音開始ボタンで開始</li>
          <li>リズムに合わせて手拍子!</li>
          <li>停止ボタンで停止</li>
          <li>再生ボタンで聞いてみよう</li>
        </ol>
      </div>
      <div class="row">
        <div class="col" id="role-model-container">
          <h3>お手本</h3>
          <%= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100", audio_data_url: "/test.mp3" %>
          <%#= render "layouts/guest_tutorial/audio_slider", slider_type: "model-audio", slider_size: "100" %>
        </div>
        <div class="col" id="collab-source-container">
          <h3>コラボ音源</h3>
          <%= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100", audio_data_url: "/test.mp3" %>
          <%#= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/guest_tutorial/_hard_help_text.html.erb
<div class="card border border-2 border-white bg-color card-shadow-dark mb-5">
  <div class="card-body text-white">
    <div class="card-text">
      <div class="mb-5">
        <h3>ポイント</h3>
        <ol>
          <li>最初に始まるクリック音に合わせてパルマ(手拍子)を叩き始めよう!</li>
          <li>ギターのメロディにつられないようにキープ!</li>
        </ol>
      </div>
      <div class="row">
        <div class="col" id="role-model-container">
          <h3>お手本</h3>
          <%= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100", audio_data_url: "/test.mp3" %>
          <%#= render "layouts/guest_tutorial/audio_slider", slider_type: "model-audio", slider_size: "100" %>
        </div>
        <div class="col" id="collab-source-container">
          <h3>コラボ音源</h3>
          <%= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100", audio_data_url: "/test.mp3" %>
          <%#= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/guest_tutorial/_level_btn.html.erb
<%= button_to "#{btn_name}", guest_tutorial_how_to_recordings_path, { method: :get, params: {level: "#{level_name}"}, class: "btn btn-custom w-100 text-start text-white fs-3 rounded-pill py-3 mb-3" } %>

app/views/layouts/guest_tutorial/_normal_help_text.html.erb
<div class="card border border-2 border-white bg-color card-shadow-dark w-75">
  <div class="card-body text-white">
    <div class="card-text">
      <div class="mb-5">
        <h3>タパとは？</h3>
        <p>ギター奏法の一つ。音をミュートしてジャカジャカと鳴らす弾き方<br>リズム出しなどに使われる。</p>
      </div>
      <%# <div class="mb-4">
        <h3>使い方説明</h3>
        <ol>
          <li>録音開始ボタンで開始</li>
          <li>リズムに合わせて手拍子!</li>
          <li>停止ボタンで停止</li>
          <li>再生ボタンで聞いてみよう</li>
        </ol>
      </div> %>
      <div class="row">
        <div class="col" id="role-model-container">
          <h3>お手本</h3>
          <%= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100", audio_data_url: "/test.mp3" %>
          <%#= render "layouts/guest_tutorial/audio_slider", slider_type: "model-audio", slider_size: "100" %>
        </div>
        <div class="col" id="collab-source-container">
          <h3>コラボ音源</h3>
          <%= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100", audio_data_url: "/test.mp3" %>
          <%#= render "layouts/guest_tutorial/audio_slider", slider_type: "audio", slider_size: "100" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/guest_tutorial/_recording_btn.html.erb
<button type="button" class="btn btn-custom btn-lg rounded-circle text-white fw-bold px-4 py-4" id="record-button">REC</button>
<button type="button" class="btn stop-btn btn-lg rounded-circle text-white fw-bold px-4 py-4 ms-5" id="stop-button" disabled>Stop</button>