config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: "user_sessions#create"
  delete 'logout', to: 'user_sessions#destroy'


  namespace :guest_tutorial, path: "tutorial" do
    resources :introductions, only: %i[index]
  end
  namespace :guest_tutorial, path: "tutorial" do
    resources :how_to_recordings, only: %i[index]
  end

  # ゲスト投稿閲覧についての設定
  scope :guest do
    resources :posts, only: %i[index show], as: :guest
  end

  resources :posts
  resources :recordings, only: %i[new create]
  resources :users, only: %i[new create]
  resource :profile, only: %i[show edit update]
  resources :password_resets, only: %i[new create edit update]

  # letter_opener_webにアクセスするためのルーティング設定
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      flash[:success] = "Logged in successfully"
      redirect_back_or_to(posts_path)
    else
      flash.now[:danger] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(login_path, flash: {primary: 'Logged out!'})
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_with url: login_path, method: :post do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<div class='bg-dark bg-gradient bg-height'>
  <h1 class="text-white  text-left ps-5 py-3 mb-5 bg-dark bg-gradient">ログイン</h1>
  <div class="container">
    <%= render partial: 'layouts/flash' %>
    <div class="row ">
      <div class=" col-md-10 offset-md-1 col-lg-8 offset-lg-2">
        <%= form_with url: login_path, local: true do |f| %>
          <div class="form-group">
            <%= f.label :email, class: "text-white" %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: "text-white" %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="actions">
            <%= f.submit 'ログイン', class: 'btn btn-custom text-white' %>
          </div>
        <% end %>
        <div class='text-center'>
          <%= link_to '登録ページへ', new_user_path %>
          <%= link_to 'パスワードをお忘れの方はこちら', new_password_reset_path %>
        </div>
      </div>
    </div>
  </div>
</div>